services:
  consumer:
    build: employeeService
    image: consumer-image
    container_name: consumer
    hostname: consumer
    ports:
      - "8080:8080"
    restart: on-failure


  producer:
    build: producer
    image: producer-image
    container_name: producer
    hostname: producer
    ports:
      - "8080:8080"
    restart: on-failure

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always